# Generated by Django 5.1.1 on 2024-09-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauthapp', '0002_user_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
