# Generated by Django 5.1.1 on 2024-10-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userauthapp', '0007_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
