# Generated by Django 5.1.1 on 2024-12-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userauthapp', '0009_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
